<?php

use GuzzleHttp\Client;
use Illuminate\Database\Seeder;
use TheRogg\Domain\Office;
use TheRogg\Domain\Party;
use TheRogg\Domain\State;
use TheRogg\Repositories\Politicians\PoliticianRepositoryInterface as PoliticianRepo;

class PoliticianSeeder extends Seeder
{
    private $politicianRepo;

    public function __construct(PoliticianRepo $politicianRepo)
    {
        $this->politicianRepo = $politicianRepo;
    }

    public function run()
    {
        Schema::drop('politicians');

        $this->seedCandidates();
        $this->seedCongress();
        $this->seedBios();
    }

    private function seedCandidates()
    {
        $politician = $this->politicianRepo->make('Lincoln Chafee', State::RI, Office::Senator, Party::Democrat);
        $politician->setBio("Lincoln Chafee is Democratic candidate for the office of President of the United States in 2016. Chafee is the former Democratic Governor of Rhode Island. First elected to the governorship as an Independent on November 2, 2010, he became the only governor not to belong to one of the major parties when he was sworn in January 4, 2011. Chafee previously belonged to the Republican Party, serving in the U.S. Senate for seven years. Initially appointed to his father's seat upon John Chafee's death in 1999, he won a six-year term in 2000. In 2006, he lost his seat to Democrat Sheldon Whitehouse. The following year, Chafee left the Republican Party to become an Independent. Then, in anticipation of a possible re-election loss in 2014, as well as his affinity for his former U.S. Senate colleague, President Barack Obama, Chafee made his second party switch, formally joining the Democratic Party on May 30, 2013. In recent candidate rankings, Crowdpac ranked Chafee as a 0.3L (L being liberal) on a scale ranging from 10L to 10C, making him the least liberal Democratic presidential candidate.");
        $politician->setIsPresidentialCandidate(true);
        $politician->save();

        $politician = $this->politicianRepo->make('Hillary Clinton', State::NY, Office::Unelected, Party::Democrat);
        $politician->setBio("Hillary Clinton is a Democratic candidate for the office of President of the United States in 2016. Clinton's run was announced by campaign chairman John Podesta in an email to donors on April 12, 2015, and followed shortly by an official campaign video entitled \"Getting Started\".  Clinton served as thesecretary of state of the United States of America from January 21, 2009, to February 1, 2013, and as a senator fromNew York from 2001 to 2009. She lost the Democraticpresidential primary nomination to Barack Obamain 2008. Clinton also served as first lady during her husband, President Bill Clinton's, two terms. She is the first former first lady to serve both in the U.S. Senate and in a president's cabinet. When the U. S. was in its formative years, a secretary of state ascending to the presidency was commonplace, but the last secretary of state to be elected to the nation's highest office was James Buchanan in 1856. In recent candidate ankings, Crowdpac ranked Clinton as a 6.5L (L being liberal) on a scale ranging from 10L to 10C, making her the third most liberal Democratic presidential candidate.");
        $politician->setIsPresidentialCandidate(true);
        $politician->save();

        $politician = $this->politicianRepo->make("Martin O'Malley", State::MD, Office::Unelected, Party::Democrat);
        $politician->setBio("Martin O'Malley is a Democratic candidate for the office of President of the United States in 2016. He made his announcement on May 30, 2015, becoming the third Democratic candidate to enter the race. O'Malley served as the governor of Maryland from January 17, 2007, to January 21, 2015. He served as the chair of the Governor's Executive Council from 2007 to 2015 and the co - chair of the Council of Governors from 2013 to 2015. Prior to his gubernatorial career, O'Malley served as the mayor of Baltimore from 1999 to 2007. O'Malley previously stated on January 8, 2015, \"I’m very seriously considering running in 2016. Right now, my primary responsibility is to move my family back to Baltimore, which I will do in another situated. \" Seventeen presidents have also served as governors. In recent candidate rankings, Crowdpac ranked O'Malley as a 6.7L (L being liberal) on a scale ranging from 10L to 10C, making him the second most liberal Democratic presidential candidate.");
        $politician->setIsPresidentialCandidate(true);
        $politician->save();

        //$politician = $this->politicianRepo->make('Bernie Sanders', State::VT, Office::Senator, Party::Democrat);
        //$politician->setBio("Bernie Sanders is a Democratic candidate for the office of President of the United States in 2016. Sanders is an independent member of the U.S. Senate from the state of Vermont. He was first elected to the Senate in 2006. Sanders calls himself a socialist and is a member of the Senate Democratic Caucus. Sanders made his formal announcement for the Democratic nomination at a press conference on April 30, 2015. His office streamed the announcement live using Periscope, a social media service which allows the streaming of video from smartphones. On May 26, 2015, Sanders made his first public appearance on the campaign trail where he reiterated his run for the presidency. During the speech, Sanders discussed economic and environmental policy at length. \"This great nation and its government belong to all of the people and not to a handful of billionaires, their super PACs and their lobbyists,\" Sanders remarked Previously, in March 2014, Sanders said that he was \"prepared to run for President\" in 2016. Sanders also told Yahoo Newsthat he does \"not wake up every morning with a burning desire to be president of the United States. And I think anybody who does should be immediately suspected as probably totally crazy.\" Sixteen senators have been elected to the presidency, including President Barack Obama (D). In recent candidate rankings, Crowdpac ranked Sanders as a 7.6L (L being liberal) on a scale ranging from 10L to 10C, making him the most liberal Democratic presidential candidate..");
        //$politician->setIsPresidentialCandidate(true);
        //$politician->save();

        $politician = $politician = $this->politicianRepo->make('Jim Webb', State::VA, Office::Unelected, Party::Democrat);
        $politician->setBio("Jim Webb is a Democratic candidate for the office of President of the United States in 2016. Webb was a U.S. senator from Virginia from January 3, 2007, to January 3, 2013. Webb served as the secretary of the Navy from 1987 to 1988 and in the United States Marines from 1968 to 1972. On July 2, 2015, Webb declared his candidacy for president in an email to supporters. He wrote, \"We need a President who understands leadership, who has a proven record of actual accomplishments, who can bring about bipartisan solutions, who can bring people from both sides to the table to get things done.\" In November 2014, Webb announced, \"I have decided to launch an Exploratory Committee to examine whether I should run for President in 2016. I made this decision after reflecting on numerous political commentaries and listening to many knowledgeable people. I look forward to listening and talking with more people in the coming months as I decide whether or not to run.\" Sixteen senators have been elected to the presidency, including President Barack Obama (D). In recent candidate rankings, Crowdpac ranked Webb as a 5.4L (L being liberal) on a scale ranging from 10L to 10C, making him the fifth most liberal Democratic presidential candidate.");
        $politician->setIsPresidentialCandidate(true);
        $politician->save();

        $politician = $this->politicianRepo->make('Joe Biden', State::DE, Office::VicePresident, Party::Democrat);
        $politician->setBio("Joe Biden is a potential candidate for the office of President of the United States in 2016. Biden is the Vice President of the United States. He and President Barack Obama were sworn in for their first terms of office on January 20, 2009. Biden was sworn in for his second term as vice president on January 20, 2013. Before becoming vice president, Biden served as a U.S. senator from Delaware from 1973 to 2009. He also ran for president in 1988 and 2008. Biden withdrew his candidacy from the 1988 race after he was found plagiarizing speeches from other politicians. He withdrew from the 2008 presidential race on January 3, 2008, after receiving support from only 1 percent of the delegates at the Iowa caucuses. Biden has hinted that he is considering a run for president in 2016 in several interviews. In July 2013, Biden said, \"I can die a happy man never having been president of the United States of America, but it doesn't mean I won't run. \" Biden later said in an interview on February 7, 2014, \"There’s no obvious reason for me why I think I should not run.\" President Barack Obama commented on Biden and Hillary Clinton when asked to compare them, stating, \"both Hillary and Joe would make outstanding presidents, and possess the qualities that are needed to be outstanding presidents.\" Fourteen vice presidents have become president, but only four were directly elected after serving as vice president. In recent candidate rankings, Crowdpac ranked Biden as a 6.7L (L being liberal) on a scale ranging from 10L to 10C, making him, if he enters the race, the sixth most liberal Democratic presidential candidate.");
        $politician->setIsPresidentialCandidate(true);
        $politician->save();

        $politician = $this->politicianRepo->make('Jeb Bush', State::FL, Office::Unelected, Party::Republican);
        $politician->setBio("Jeb Bush is a candidate for the office of President of the United States in 2016. He officially announced his campaign on June 15, 2015, in Miami. Bush served as the governor of Florida from 1999 to 2007. He is the son of President George H.W. Bush and the younger brother of President George W. Bush. Bush is the first brother of a president to run for the office since Robert Kennedy in 1968. Bush posted the following comments on his Facebook page on December 16, 2014: \"I have decided to actively explore the possibility of running for President of the United States. In January, I also plan to establish a Leadership PAC that will help me facilitate conversations with citizens across America to discuss the most critical challenges facing our exceptional nation. The PAC’s purpose will be to support leaders, ideas and policies that will expand opportunity and prosperity for all Americans. In the coming months, I hope to visit with many of you and have a conversation about restoring the promise of America.\" On April 19, 2013, former President George W. Bush said that he hoped his brother Jeb would consider running for president and would not \"be afraid of entering the arena\" because of the family name. Seventeen presidents, including George W. Bush, have also served as governors. In recent candidate rankings, Crowdpac ranked Bush as a 5.1C (C being conservative) on a scale ranging from 10L to 10C, making him the ninth most conservative Republican presidential candidate. Bush received a grade of a \"B/85\" from the Leadership Project for America PAC, a conservative political action committee.");
        $politician->setIsPresidentialCandidate(true);
        $politician->save();

        $politician = $this->politicianRepo->make('Ben Carson', State::MI, Office::Unelected, Party::Republican);
        $politician->setBio("Ben Carson is a Republican candidate for the office of President of the United States in 2016. Carson, a retired paediatric neurosurgeon, gained popularity with conservatives after his speech at the 2013 National Prayer Breakfast, where he expressed his dissatisfaction with President Barack Obama's policies and the direction of the country. At age 33, Carson became the director of pediatric neurosurgery at Johns Hopkins University, making him the youngest major division director in the hospital's history. He was also a professor of neurosurgery, oncology, plastic surgery and pediatric medicine. On May 3, 2015, Carson announced his bid for the presidency the day before his scheduled campaign kickoff in Detroit, Michigan. \"I'm willing to be a part of the equation, and, therefore, I'm announcing my candidacy for president of the United States,\" discussed Carson in an interview with Sinclair Broadcasting. Carson announced that he formed a presidential exploratory committee on March 3, 2015. He said, \"I very much need and look forward to your feedback and help. All of us are frustrated with the way Washington has let us down. The career politicians simply don't understand the disappointment, anger and pain in real America. As they cater to the special interests first, they don't even seem to care about how failed policies actually affect us, the people of the United States. I think it's time for us to show them how much we do care about the job they are doing. ...If I believe that I have your support and your commitment to help, I will run for president to lead this great country to a brighter future. \" Only three previous presidents had no prior political experience, but all three of them, Zachary Taylor, Ulysses S. Grant and Dwight Eisenhower, served as high-ranking military officials. In recent candidate rankings, Crowdpac ranked Carson as a 7.5C (C being conservative) on a scale ranging from 10L to 10C, making him the fourth most conservative Republican presidential candidate. Carson received a grade of a \"B -/82\" from the Leadership Project for America PAC, a conservative political action committee");
        $politician->setIsPresidentialCandidate(true);
        $politician->save();

        $politician = $this->politicianRepo->make('Chris Christie', State::NJ, Office::Governor, Party::Republican);
        $politician->setBio("Chris Christie is a Republican candidate for the office of President of the United States in 2016. On June 30, 2015, Christie made his announcement at Livingston High School, which he graduated from in 1980. Christie is the current governor of New Jersey. He was first elected in 2009. Prior to his gubernatorial bid, Christie served as the U.S. attorney for New Jersey from 2002 to 2008. When asked on August 14, 2014, whether he would enter the presidential race in 2016, Christie stated, \"I'm thinking about it. It is an enormous decision to make not only for me, but my family. Probably by the end of this year or the beginning of next I’ll decide. \" In 2012, Christie made visits to key states, including Iowa,New Hampshire and South Carolina. He also appeared at a national fundraising event in New York City on September 23, 2013. There have been 17 presidents who previously served as governors. In recent candidate rankings, Crowdpac ranked Christie as a 3.4C (C being conservative) on a scale ranging from 10L to 10C, making him the third least conservative Republican presidential candidate. Christie received a grade of a \"C -/70\" from the Leadership Project for America PAC, a conservative political action committee.");
        $politician->setIsPresidentialCandidate(true);
        $politician->save();

        $politician = $this->politicianRepo->make('Jim Gilmore', State::VA, Office::Unelected, Party::Republican);
        $politician->setBio("Jim Gilmore is a candidate for the office of President of the United States in 2016. On July 29, 2015, Gilmore filed paperwork with the Federal Election Commission to run for president. He also released a web video formally announcing his candidacy on July 30, 2015. Gilmore served as attorney general of Virginia from 1994 to 1997. From 1998 to 2002, he was the governor of Virginia. He has chaired or been a member of numerous boards, committees and organizations, including the National Rifle Association, where he is currently on the board. He is also the President and CEO of the conservative think tank Free Congress Foundation. Gilmore's announcement that he was entering the 2016 presidential race was expected, as he mentioned his intentions to announce in early August to the Richmond Times - Dispatch in July. This is also not his first bid for the presidency. He had begun to campaign in 2007 for the 2008 GOP presidential nomination, but dropped out of the race early, instead going on to race unsuccessfully against Mark Warner(D) for a seat in the U. S. Senate in the 2008 Virginia General Election");
        $politician->setIsPresidentialCandidate(true);
        $politician->save();

        //$politician = $this->politicianRepo->make('Lindsey Graham', State::SC, Office::Senator, Party::Republican);
        //$politician->setBio("Lindsey Graham is a Republican candidate for the office of President of the United States in 2016. He made his announcement in his home town of Central, South Carolina, on June 1, 2015. During his announcement, he focused on his experience with foreign policy and national defense. Graham is a Republican member of the U. S. Senate from the state of South Carolina. He was first elected to the Senate in 2002 and most recently won re - election in 2014. Graham also represented South Carolina's 3rd Congressional District in the U.S. House of Representatives from January 3, 1995, to January 3, 2003. On January 18, 2015, Graham said that he was considering a run for president in 2016. He noted that his foreign policy knowledge qualifies him to run. He said, \"I think the world is falling apart, and I've been more right than wrong when it comes to foreign policy. But we'll see. \" In recent candidate rankings, Crowdpac ranked Graham as a 4.6C (C being conservative) on a scale ranging from 10L to 10C, making him the fifth least conservative Republican presidential candidate. He received a grade of \"B / 84\" from the Leadership Project for America PAC, a conservative political action committee.");
        //$politician->setIsPresidentialCandidate(true);
        //$politician->save();

        $politician = $this->politicianRepo->make('Mike Huckabee', State::AR, Office::Unelected, Party::Republican);
        $politician->setBio("Mike Huckabee is a candidate for the office of President of the United States in 2016. Huckabee was the 44th Governor of Arkansas from 1996 to 2007 and a 2008 presidential candidate. On January 3, 2015, Huckabee announced that he would no longer host his Fox News talk show Huckabee. He said, \"As much as I have loved doing the show, I cannot bring myself to rule out another presidential run. “Oh be clear, I'm not making that announcement right now and my timetable is still just what wait was before, later this spring, but I agree with Fox this is the right thing and now is the right time. \" Huckabee officially announced his presidential run in his hometown of Hope, Arkansas, on May 5, 2015. After describing his early life in the town, he declared, \"So it seems perfectly fitting that it would be here that I announce that I am a candidate for president of the United States of America. \" When asked on December 22, 2013, whether he would be interested in another run for the presidency, Huckabee said, \"It would be, frankly, dishonest to say no. \" Since his 2008 bid for the presidency, Huckabee's popularity has grown due to his Fox News talk show Huckabee and the founding of the Huck PAC, which provides funding to key congressional campaigns across the country. Seventeen governors have served as president. In recent candidate rankings, Crowdpac ranked Huckabee as a 6.7C(C being conservative) on a scale ranging from 10L to 10C, making him the seventh most conservative Republican presidential candidate. Huckabee received a grade of a \"D / 63\" from the Leadership Project for America PAC, a conservative political action committee.");
        $politician->setIsPresidentialCandidate(true);
        $politician->save();

        //$politician = $this->politicianRepo->make('Ted Cruz', State::TX, Office::Senator, Party::Republican);
        //$politician->setBio("Ted Cruz is a Republican candidate for the office of President of the United States in 2016. Cruz announced the launch of his campaign in a tweet on March 23, 2015. Sixteen senators have been elected president, including Barack Obama. Cruz is a Republican member of the United States Senate from Texas. He won election to the Senate on November 6, 2012. Cruz, who was born in Canada, has an American mother and a Cuban father; in 2014, he officially renounced his Canadian dual citizenship. \"The renunciation became official on May 14, roughly 9 months after he learned he wasn't only an American,\" according to the Dallas Morning News. \"The U. S. Constitution requires presidents to be 'natural born' citizens, which is commonly believed to include Americans born with the right to citizenship, even if they were not born on American soil specifically,\" according to Time. In recent candidate rankings, Crowdpac ranked Cruz as a 9.5C(C being conservative) on a scale ranging from 10L to 10C, making him the second most conservative Republican presidential candidate. Cruz received a grade of a \"B / 86\" from the Leadership Project for America PAC, a conservative political action committee.");
        //$politician->setIsPresidentialCandidate(true);
        //$politician->save();

        $politician = $this->politicianRepo->make('Carly Fiorina', State::CA, Office::Unelected, Party::Republican);
        $politician->setBio("Bobby Jindal is a candidate for the office of President of the United States in 2016. Jindal is the governor of Louisiana. He was first elected in 2007 and was re - elected to the position on October 22, 2011. He previously served as a member of the U. S. House of Representatives, representing Louisiana's 1st Congressional District from 2004 to 2008. Jindal was considered a possible candidate for Mitt Romney's vice presidential running mate in 2012, but Romney chose Paul Ryan instead. Jindal announced his bid for the presidency today through a press release on his website. \"My name is Bobby Jindal, and I am running for President of the United States of America,\" the announcement read. The post included videos filming his family's reaction to the news. Previously, during a lunch with conservative bloggers on September 16, 2014, Jindal said, \"I'm not going to be coy, I'm thinking about running for president and praying about it. \"  Seventeen presidents have also served as governors. In recent candidate rankings, Crowdpac ranked Jindal as a 4.8C (C being conservative) on a scale ranging from 10L to 10C, making him the tenth most conservative Republican presidential candidate. Jindal received a grade of a \"A -/91\" from the Leadership Project for America PAC, a conservative political action committee.");
        $politician->setIsPresidentialCandidate(true);
        $politician->save();

        $politician = $this->politicianRepo->make('John Kasich', State::OH, Office::Governor, Party::Republican);
        $politician->setBio("John Kasich is a Republican candidate for the office of President of the United States in 2016. John Kasich is the governor of Ohio. He previously served in the Ohio State Senate from 1979 to 1983 and in the U.S. House of Representatives from 1983 to 2001, representing Ohio's 12th congressional District. Kasich also ran unsuccessfully for president of the United States in 2000. Kasich officially announced his bid for the presidency on July 21, 2015, making him the 16th major Republican candidate to enter the race. He made his announcement at Ohio State University in Columbus, Ohio, where he earned a B. A. in political science in 1974. Previously, in March 2014, Kasich said that he was \"just not interested\" in running for the presidency, but in an interview with ABC News on December 7, 2014, he would not explicitly deny plans to run. When asked about the possibility, Kasich responded, \"Well, George, well, look, you know, you knew you were never going to get a good answer out of me here today. \" Kasich has earned both support and criticism from fellow Republicans for his more moderate political philosophy. He supported Common Core education standards, a path to citizenship for illegal immigrants and expansions for Medicaid in Ohio. Kasich's support in his home state could offer him a significant advantage, if he chooses to run, as no candidate who has lost Ohio has been able to win the presidency in over 50 years. In recent candidate rankings, Crowdpac ranked Kasich as an 4.0C (C being conservative) on a scale ranging from 10L to 10C, making him the fourth least conservative Republican presidential candidate. Kasich received a grade of a \"B -/80\" from the Leadership Project for America PAC, a conservative political action committee");
        $politician->setIsPresidentialCandidate(true);
        $politician->save();

        $politician = $this->politicianRepo->make('George Pataki', State::NY, Office::Unelected, Party::Republican);
        $politician->setBio("George Pataki is a Republican candidate for the office of President of the United States in 2016. On May 28, 2015, Pataki announced his presidential bid via a video posted on his campaign website, before speaking to a crowd of supporters in New Hampshire. Pataki served as the governor of New York for three terms between 1995 and 2007. Pataki has since worked for the law firm, Chadbourne & Parke LLP, and founded a consulting firm with his former Chief of Staff John Cahill. Pataki made several trips to New Hampshire at the end of 2014, stating he was \"very seriously\" considering a run for president. In recent candidate rankings, Crowdpac ranked Pataki as a 1.1C (C being conservative) on a scale ranging from 10L to 10C, making him the second least conservative Republican presidential candidate. He received a grade of \"D -/61\" from the Leadership Project for America PAC, a conservative political action committee.");
        $politician->setIsPresidentialCandidate(true);
        $politician->save();

        //$politician = $this->politicianRepo->make('Rand Paul', State::KY, Office::Senator, Party::Republican);
        //$politician->setBio("Rand Paul is a Republican candidate for the office of President of the United States in 2016. Paul is a Republican member of the U.S. Senate from the state of Kentucky. Prior to being elected to Congress in 2010, Paul worked as an ophthalmologist. As speculation swirled as to whether or not Paul would announce in early April, his campaign released a video on April 6, 2015, indicating an announcement would be made on April 7, 2015, at a rally in Louisville, Ky. Two hours before the rally, his website was updated with the following quote from Paul, \"I am running for president to return our country to the principles of liberty and limited government. \" Previously, on December 8, 2013, Paul said that his family would determine whether or not he would run for president, claiming, \"The thought has crossed my mind... I'm not ready to make a decision t. \" Former Texas Rep. Ron Paul (R), Rand Paul's father, ran for the presidency three times, including once as a Libertarian in 1988. There have been 16 U. S. senators elected to the presidency, including President Barack Obama(D). In recent candidate rankings, Crowdpac ranked Paul as a 10 + C(C being conservative) on a scale ranging from 10L to 10C, making him the most conservative Republican presidential candidate. Paul received a grade of a \"B -/82\" from the Leadership Project for America PAC, a conservative political action committee.");
        //$politician->setIsPresidentialCandidate(true);
        //$politician->save();

        $politician = $this->politicianRepo->make('Rick Perry', State::TX, Office::Unelected, Party::Republican);
        $politician->setBio("Rick Perry is a Republican candidate for the office of President of the United States in 2016. Rick Perry served as the governor of Texas from December 2000 to January 2015. Perry also ran for the Republican nomination for president of the United States in the 2012 presidential election. Perry announced his candidacy on June 4, 2015, via a video posted to his campaign website. On September 11, 2014, Perry responded to a question about his candidacy in 2016, stating, \"I may not run in 2016, but I've spent the last 20 - plus months preparing. If I don't run, it won't be because I'm not prepared. \"  Prior to the 2016 election, there were 17 presidents who previously served as governors. In recent candidate rankings, Crowdpac ranked Perry as a 7.0C(C being conservative) on a scale ranging from 10L to 10C, making him the fifth most conservative Republican presidential candidate. Perry received a grade of a \"B / 84\" from the Leadership Project for America PAC, a conservative political action committee. ");
        $politician->setIsPresidentialCandidate(true);
        $politician->save();

        //$politician = $this->politicianRepo->make('Marco Rubio', State::FL, Office::Senator, Party::Republican);
        //$politician->setBio("Marco Rubio is a Republican candidate for the office of President of the United States in 2016. On April 13, 2015, Rubio announced his presidential run on a conference call with donors. He referred to himself as \"uniquely qualified\" for the nomination. The call came hours before a scheduled campaign rally in Miami. Rubio is a Republican member of the U. S. Senate from the state of Florida. He was first elected in 2010. Rubio was a member of the Florida House of Representatives from 2000 to 2008. Previously, in May 2014, when ABC reporter Jonathan Karl asked Rubio if he thought he was ready to be president, Rubio said, “I do … but I think that's true for multiple other people that would want to run … I mean, I'll be 43 this month, but the other thing that perhaps people don't realize, I've served now in public office for the better part of 14 years. Most importantly, I think a president has to have a clear vision of where the country needs to go and clear ideas about how to get it there and I think we're very blessed in our party to have a number of people that fit that criteria. \" Sixteen senators have been elected to the presidency, including President Barack Obama. In recent candidate rankings, Crowdpac ranked Rubio as a 6.5C(C being conservative) on a scale ranging from 10L to 10C, making him the eighth most conservative Republican presidential candidate. Rubio received a grade of a \"A -/92\" from the Leadership Project for America PAC, a conservative political action committee. ");
        //$politician->setIsPresidentialCandidate(true);
        //$politician->save();

        $politician = $this->politicianRepo->make('Rick Santorum', State::PA, Office::Unelected, Party::Republican);
        $politician->setBio("Rick Santorum is a candidate for the office of President of the United States in 2016. On May 27, 2015, Santorum announced his presidential run in Butler, Pennsylvania. Santorum served as a U. S. senator from Pennsylvania from January 3, 1995, to January 3, 2007. He also served as a member of the United States House of Representatives from Pennsylvania's 18th Congressional District from January 3, 1991, to January 3, 1995.[3] He ran for the Republican presidential nomination in 2012, but he ended his campaign on April 10, 2012. During a December 2014 interview with The Washington Post, Santorum indicated that he would run in 2016. He said, \"America loves an underdog. We're definitely the underdog in this race. \" Sixteen senators have been elected to the presidency, including President Barack Obama. In recent candidate rankings, Crowdpac ranked Santorum as a 4.8C (C being conservative) on a scale ranging from 10L to 10C, making him the eleventh most conservative Republican presidential candidate. Santorum received a grade of a \"B -/81\" from the Leadership Project for America PAC, a conservative political action committee. ,'18th'");
        $politician->setIsPresidentialCandidate(true);
        $politician->save();

        $politician = $this->politicianRepo->make('Donald Trump', State::NY, Office::Unelected, Party::Republican);
        $politician->setBio("Donald Trump is a Republican candidate for the office of President of the United States in 2016. On June 16, 2015, Trump announced his bid for the presidency at Trump Tower in New York City. Trump said, \"I am officially running for president of the United States, and we are going to make our country great again. \" In recent candidate rankings, Crowdpac ranked Trump as a 0.4L(L being liberal) on a scale ranging from 10L to 10C, making him the least conservative Republican presidential candidate and slightly more liberal than Democratic candidate Lincoln Chafee. He received a grade of \"F / 57\" from the Leadership Project for America PAC, a conservative political action committee. ");
        $politician->setIsPresidentialCandidate(true);
        $politician->save();

        $politician = $this->politicianRepo->make('Scott Walker', State::WI, Office::Governor, Party::Republican);
        $politician->setBio("Scott Walker is a candidate for the office of President of the United States in 2016. He announced his candidacy on July 13, 2015. Walker is the 45th Governor of Wisconsin and was first elected to the office in 2010. During his first term, Walker proposed Wisconsin Act 10, which restricted the ability of public workers to engage in public bargaining. The act drew massive protests, mainly organized by unions. Opponents of the measure successfully forced Walker to face a recall election on June 5, 2012. Walker survived the recall election, defeating Tom Barrett(D) 53 percent to 46 percent. In doing so, Walker became the first governor to survive a recall. He then won re - election on November 4, 2014. Prior to serving as governor, Walker was a member of the Wisconsin State Assembly from 1993 to 2002 and Milwaukee County Executive from 2002 to 2010. He attended Marquette University, but he did not earn his bachelor's degree, choosing instead to leave school for a job with the American Red Cross during his senior year. He explained the decision saying, \"The reason I went to college, in large part, was not just to get an education for an education's sake, but to get a job. Someday, maybe in the next few years, I'll embark on finishing my degree.” Walker filed paperwork with the Federal Election Commission on July 2, 2015. However, he did not officially announce his campaign until July 13, 2015. Walker released an early morning video on social media confirming his run for the presidency. Previously, when asked on December 1, 2013, if he was considering entering the presidential race, Walker said, \"I'm running for governor... we'll see what happens after that. I've got to look at my state... for now I'm focused on being governor.\" Then, on February 5, 2015, when Martha Raddatz asked if he will run for president, Walker said, \"I'll just tell you one thing. After three elections for governor in four years in a state that hasn't gone Republican since 1984 for president, I wouldn't bet against me on anything.\" In recent candidate rankings, Crowdpac ranked Walker as an 8.8C(C being conservative) on a scale ranging from 10L to 10C, making him the third most conservative Republican presidential candidate. Walker received a grade of a \"A-/91\" from the Leadership Project for America PAC, a conservative political action committee.");
        $politician->setIsPresidentialCandidate(true);
        $politician->save();
    }

    private function seedCongress()
    {
        $client = new Client();

        $response = $client->get('https://www.govtrack.us/api/v2/role?current=true&limit=600');
        $json     = json_decode($response->getBody())->objects;

        foreach ($json as $politicianJson)
        {
            $firstName  = $politicianJson->person->firstname;
            $middleName = $politicianJson->person->middlename;
            $lastName   = $politicianJson->person->lastname;

            if (empty($middleName))
                $name = $firstName . ' ' . $lastName;
            else
                $name = $firstName . ' ' . $middleName . ' ' . $lastName;

            $district      = $politicianJson->district;
            $party         = $politicianJson->party;
            $roleTypeLabel = $politicianJson->role_type_label;
            $state         = $politicianJson->state;
            $bioGuideId    = $politicianJson->person->bioguideid;
            $govTrackId    = $politicianJson->person->id;

            $politician = $this->politicianRepo->make($name, $state, $roleTypeLabel, $party, $district, $bioGuideId, $govTrackId);

            if ($politician->getName() == 'Bernard Sanders' || $politician->getName() == 'Ted Cruz' || $politician->getName() == 'Lindsey O. Graham' || $politician->getName() == 'Rand Paul' || $politician->getName() == 'Marco Rubio')
            {
                $politician->setIsPresidentialCandidate(true);
                $this->politicianRepo->save($politician);
            }
        }
    }

    private function seedBios() { }

    private $bios = [
        [
            'govTrackId' => '400034',
            'bio'        => "BLUNT, Roy, a Senator and a Representative from Missouri; born in Niangua, Webster County, Mo., January 10, 1950; graduated Southwest Baptist University, Bolivar, Mo., B.A., 1970; graduated Missouri State University, Springfield, Mo., M.A., 1972; high school history teacher; clerk and chief election officer, Greene County, Mo. 1973-1984; Missouri state secretary of state 1984-1993; president, Southwest Baptist University, Bolivar, Mo. 1993-1996; elected as a Republican to the One Hundred Fifth and to the six succeeding Congresses (January 3, 1997-January 3, 2011); majority whip (One Hundred Eighth through One Hundred Ninth Congresses); acting majority leader (One Hundred Ninth Congress, September 28, 2005-February 2, 2006); minority whip (One Hundred Tenth Congress); was not a candidate for reelection to the House of Representatives but was elected as a Republican to the United States Senate in 2010 for the term ending January 3, 2017; vice-chair, Republican Conference (2012-); chair, Committee on Rules and Administration (One Hundred Fourteenth Congress)."
        ],
        [
            'govTrackId' => '400040',
            'bio'        => "BOOZMAN, John, a Senator and a Representative from Arkansas; born in Shreveport, La., December 10, 1950; graduated from Northside High School, Fort Smith, Ark.; attended the University of Arkansas, Fayetteville, Ark., 1969-1972; graduated Southern College of Optometry, 1977; optometrist; business owner; rancher; member of the Rogers, Ark., school board; elected as a Republican to the One Hundred Seventh Congress by special election to fill the vacancy caused by the resignation of United States Representative Asa Hutchinson; reelected to the four succeeding Congresses (November 20, 2001-January 3, 2011); was not a candidate for reelection to the House of Representatives but was elected as a Republican to the United States Senate in 2010 for the term ending January 3, 2017."
        ],
        [
            'govTrackId' => '400054',
            'bio'        => "BURR, Richard M., a Senator and a Representative from North Carolina; born in Charlottesville, Albemarle County, Va., November 30, 1955; graduated from Reynolds High School, Winston-Salem, N.C., 1974; B.A., Wake Forest University, Winston-Salem, N.C., 1978; unsuccessful candidate for election to the One Hundred Third Congress in 1992; elected as a Republican to the One Hundred Fourth and to the four succeeding Congresses (January 3, 1995-January 3, 2005); was not a candidate for reelection to the House of Representatives, but was elected to the United States Senate in 2004; reelected in 2010 for the term ending January 3, 2017; chair, Select Committee on Intelligence (One Hundred Fourteenth Congress)."
        ],
        [
            'govTrackId' => '400194',
            'bio'        => "ISAKSON, Johnny, a Senator and a Representative from Georgia; born in Atlanta, Fulton County, Ga., December 28, 1944; graduated from the University of Georgia, Athens, Ga., 1966; served in the Georgia Air National Guard 1966-1972; member of the Georgia state general assembly, 1976-1990; unsuccessful candidate for election as Governor of Georgia 1990; member of the Georgia state senate 1993-1996; unsuccessful candidate for election to the United States Senate in 1996; chair of the Georgia board of education 1996; elected as a Republican to the One Hundred Sixth Congress by special election to fill the vacancy created when United States Representative Newt Gingrich did not take his seat in the One Hundred Sixth Congress; reelected to the two succeeding Congresses (February 23, 1999-January 3, 2005); was not a candidate for reelection to the House of Representatives, but was elected to the United States Senate in 2004; reelected in 2010 for the term ending January 3, 2017; chair, Committee on Veterans’ Affairs (One Hundred Fourteenth Congress), Select Committee on Ethics (One Hundred Fourteenth Congress)."
        ],
        [
            'govTrackId' => '400222',
            'bio'        => "KIRK, Mark Steven, a Senator and a Representative from Illinois; born in Champaign, Champaign County, Ill., September 15, 1959; B.A., Cornell University, Ithaca, N.Y., 1981; M.S., London School of Economics, London, England, 1982; J.D., Georgetown University, Washington, D.C., 1992; United States Naval Reserves, 1989 to present; lawyer, private practice; staff member for United States Representative John Porter of Illinois, 1984-1990; special assistant, United States Department of State, 1992-1993; staff member for United States House of Representatives International Relations Committee, 1995; elected as a Republican to the One Hundred Seventh and to the four succeeding Congresses, and served from January 3, 2001, until his resignation on November 29, 2010; was not a candidate for reelection to the House of Representatives but was elected as a Republican to the United States Senate in the November 2, 2010, special election to the term ending January 3, 2011, a seat previously held by appointed Senator Roland Burris, and at the same time elected in the general election for the six-year term ending January 3, 2017; took the oath of office on November 29, 2010."
        ],
    ];

    private $temp = [
        [
            'govTrackId' => '',
            'bio'        => ""
        ],
    ];
}